/* soapMediaBindingProxy.h
   Generated by gSOAP 2.8.23 from media.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapMediaBindingProxy_H
#define soapMediaBindingProxy_H
#include "soapH.h"

class SOAP_CMAC MediaBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'MediaBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in media.h (non-static)
	/// Constructor
	MediaBindingProxy();
	/// Construct from another engine state
	MediaBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	MediaBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	MediaBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	MediaBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	MediaBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor deletes deserialized data and engine context
	virtual	~MediaBindingProxy();
	/// Initializer used by constructors
	virtual	void MediaBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns1__GetServiceCapabilities, ns1__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetVideoSources' (returns error code or SOAP_OK)
	virtual	int GetVideoSources(_ns1__GetVideoSources *ns1__GetVideoSources, _ns1__GetVideoSourcesResponse &ns1__GetVideoSourcesResponse) { return this->GetVideoSources(NULL, NULL, ns1__GetVideoSources, ns1__GetVideoSourcesResponse); }
	virtual	int GetVideoSources(const char *endpoint, const char *soap_action, _ns1__GetVideoSources *ns1__GetVideoSources, _ns1__GetVideoSourcesResponse &ns1__GetVideoSourcesResponse);

	/// Web service operation 'GetAudioSources' (returns error code or SOAP_OK)
	virtual	int GetAudioSources(_ns1__GetAudioSources *ns1__GetAudioSources, _ns1__GetAudioSourcesResponse &ns1__GetAudioSourcesResponse) { return this->GetAudioSources(NULL, NULL, ns1__GetAudioSources, ns1__GetAudioSourcesResponse); }
	virtual	int GetAudioSources(const char *endpoint, const char *soap_action, _ns1__GetAudioSources *ns1__GetAudioSources, _ns1__GetAudioSourcesResponse &ns1__GetAudioSourcesResponse);

	/// Web service operation 'GetAudioOutputs' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputs(_ns1__GetAudioOutputs *ns1__GetAudioOutputs, _ns1__GetAudioOutputsResponse &ns1__GetAudioOutputsResponse) { return this->GetAudioOutputs(NULL, NULL, ns1__GetAudioOutputs, ns1__GetAudioOutputsResponse); }
	virtual	int GetAudioOutputs(const char *endpoint, const char *soap_action, _ns1__GetAudioOutputs *ns1__GetAudioOutputs, _ns1__GetAudioOutputsResponse &ns1__GetAudioOutputsResponse);

	/// Web service operation 'CreateProfile' (returns error code or SOAP_OK)
	virtual	int CreateProfile(_ns1__CreateProfile *ns1__CreateProfile, _ns1__CreateProfileResponse &ns1__CreateProfileResponse) { return this->CreateProfile(NULL, NULL, ns1__CreateProfile, ns1__CreateProfileResponse); }
	virtual	int CreateProfile(const char *endpoint, const char *soap_action, _ns1__CreateProfile *ns1__CreateProfile, _ns1__CreateProfileResponse &ns1__CreateProfileResponse);

	/// Web service operation 'GetProfile' (returns error code or SOAP_OK)
	virtual	int GetProfile(_ns1__GetProfile *ns1__GetProfile, _ns1__GetProfileResponse &ns1__GetProfileResponse) { return this->GetProfile(NULL, NULL, ns1__GetProfile, ns1__GetProfileResponse); }
	virtual	int GetProfile(const char *endpoint, const char *soap_action, _ns1__GetProfile *ns1__GetProfile, _ns1__GetProfileResponse &ns1__GetProfileResponse);

	/// Web service operation 'GetProfiles' (returns error code or SOAP_OK)
	virtual	int GetProfiles(_ns1__GetProfiles *ns1__GetProfiles, _ns1__GetProfilesResponse &ns1__GetProfilesResponse) { return this->GetProfiles(NULL, NULL, ns1__GetProfiles, ns1__GetProfilesResponse); }
	virtual	int GetProfiles(const char *endpoint, const char *soap_action, _ns1__GetProfiles *ns1__GetProfiles, _ns1__GetProfilesResponse &ns1__GetProfilesResponse);

	/// Web service operation 'AddVideoEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int AddVideoEncoderConfiguration(_ns1__AddVideoEncoderConfiguration *ns1__AddVideoEncoderConfiguration, _ns1__AddVideoEncoderConfigurationResponse &ns1__AddVideoEncoderConfigurationResponse) { return this->AddVideoEncoderConfiguration(NULL, NULL, ns1__AddVideoEncoderConfiguration, ns1__AddVideoEncoderConfigurationResponse); }
	virtual	int AddVideoEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__AddVideoEncoderConfiguration *ns1__AddVideoEncoderConfiguration, _ns1__AddVideoEncoderConfigurationResponse &ns1__AddVideoEncoderConfigurationResponse);

	/// Web service operation 'AddVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int AddVideoSourceConfiguration(_ns1__AddVideoSourceConfiguration *ns1__AddVideoSourceConfiguration, _ns1__AddVideoSourceConfigurationResponse &ns1__AddVideoSourceConfigurationResponse) { return this->AddVideoSourceConfiguration(NULL, NULL, ns1__AddVideoSourceConfiguration, ns1__AddVideoSourceConfigurationResponse); }
	virtual	int AddVideoSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__AddVideoSourceConfiguration *ns1__AddVideoSourceConfiguration, _ns1__AddVideoSourceConfigurationResponse &ns1__AddVideoSourceConfigurationResponse);

	/// Web service operation 'AddAudioEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int AddAudioEncoderConfiguration(_ns1__AddAudioEncoderConfiguration *ns1__AddAudioEncoderConfiguration, _ns1__AddAudioEncoderConfigurationResponse &ns1__AddAudioEncoderConfigurationResponse) { return this->AddAudioEncoderConfiguration(NULL, NULL, ns1__AddAudioEncoderConfiguration, ns1__AddAudioEncoderConfigurationResponse); }
	virtual	int AddAudioEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__AddAudioEncoderConfiguration *ns1__AddAudioEncoderConfiguration, _ns1__AddAudioEncoderConfigurationResponse &ns1__AddAudioEncoderConfigurationResponse);

	/// Web service operation 'AddAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int AddAudioSourceConfiguration(_ns1__AddAudioSourceConfiguration *ns1__AddAudioSourceConfiguration, _ns1__AddAudioSourceConfigurationResponse &ns1__AddAudioSourceConfigurationResponse) { return this->AddAudioSourceConfiguration(NULL, NULL, ns1__AddAudioSourceConfiguration, ns1__AddAudioSourceConfigurationResponse); }
	virtual	int AddAudioSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__AddAudioSourceConfiguration *ns1__AddAudioSourceConfiguration, _ns1__AddAudioSourceConfigurationResponse &ns1__AddAudioSourceConfigurationResponse);

	/// Web service operation 'AddPTZConfiguration' (returns error code or SOAP_OK)
	virtual	int AddPTZConfiguration(_ns1__AddPTZConfiguration *ns1__AddPTZConfiguration, _ns1__AddPTZConfigurationResponse &ns1__AddPTZConfigurationResponse) { return this->AddPTZConfiguration(NULL, NULL, ns1__AddPTZConfiguration, ns1__AddPTZConfigurationResponse); }
	virtual	int AddPTZConfiguration(const char *endpoint, const char *soap_action, _ns1__AddPTZConfiguration *ns1__AddPTZConfiguration, _ns1__AddPTZConfigurationResponse &ns1__AddPTZConfigurationResponse);

	/// Web service operation 'AddVideoAnalyticsConfiguration' (returns error code or SOAP_OK)
	virtual	int AddVideoAnalyticsConfiguration(_ns1__AddVideoAnalyticsConfiguration *ns1__AddVideoAnalyticsConfiguration, _ns1__AddVideoAnalyticsConfigurationResponse &ns1__AddVideoAnalyticsConfigurationResponse) { return this->AddVideoAnalyticsConfiguration(NULL, NULL, ns1__AddVideoAnalyticsConfiguration, ns1__AddVideoAnalyticsConfigurationResponse); }
	virtual	int AddVideoAnalyticsConfiguration(const char *endpoint, const char *soap_action, _ns1__AddVideoAnalyticsConfiguration *ns1__AddVideoAnalyticsConfiguration, _ns1__AddVideoAnalyticsConfigurationResponse &ns1__AddVideoAnalyticsConfigurationResponse);

	/// Web service operation 'AddMetadataConfiguration' (returns error code or SOAP_OK)
	virtual	int AddMetadataConfiguration(_ns1__AddMetadataConfiguration *ns1__AddMetadataConfiguration, _ns1__AddMetadataConfigurationResponse &ns1__AddMetadataConfigurationResponse) { return this->AddMetadataConfiguration(NULL, NULL, ns1__AddMetadataConfiguration, ns1__AddMetadataConfigurationResponse); }
	virtual	int AddMetadataConfiguration(const char *endpoint, const char *soap_action, _ns1__AddMetadataConfiguration *ns1__AddMetadataConfiguration, _ns1__AddMetadataConfigurationResponse &ns1__AddMetadataConfigurationResponse);

	/// Web service operation 'AddAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int AddAudioOutputConfiguration(_ns1__AddAudioOutputConfiguration *ns1__AddAudioOutputConfiguration, _ns1__AddAudioOutputConfigurationResponse &ns1__AddAudioOutputConfigurationResponse) { return this->AddAudioOutputConfiguration(NULL, NULL, ns1__AddAudioOutputConfiguration, ns1__AddAudioOutputConfigurationResponse); }
	virtual	int AddAudioOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__AddAudioOutputConfiguration *ns1__AddAudioOutputConfiguration, _ns1__AddAudioOutputConfigurationResponse &ns1__AddAudioOutputConfigurationResponse);

	/// Web service operation 'AddAudioDecoderConfiguration' (returns error code or SOAP_OK)
	virtual	int AddAudioDecoderConfiguration(_ns1__AddAudioDecoderConfiguration *ns1__AddAudioDecoderConfiguration, _ns1__AddAudioDecoderConfigurationResponse &ns1__AddAudioDecoderConfigurationResponse) { return this->AddAudioDecoderConfiguration(NULL, NULL, ns1__AddAudioDecoderConfiguration, ns1__AddAudioDecoderConfigurationResponse); }
	virtual	int AddAudioDecoderConfiguration(const char *endpoint, const char *soap_action, _ns1__AddAudioDecoderConfiguration *ns1__AddAudioDecoderConfiguration, _ns1__AddAudioDecoderConfigurationResponse &ns1__AddAudioDecoderConfigurationResponse);

	/// Web service operation 'RemoveVideoEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveVideoEncoderConfiguration(_ns1__RemoveVideoEncoderConfiguration *ns1__RemoveVideoEncoderConfiguration, _ns1__RemoveVideoEncoderConfigurationResponse &ns1__RemoveVideoEncoderConfigurationResponse) { return this->RemoveVideoEncoderConfiguration(NULL, NULL, ns1__RemoveVideoEncoderConfiguration, ns1__RemoveVideoEncoderConfigurationResponse); }
	virtual	int RemoveVideoEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveVideoEncoderConfiguration *ns1__RemoveVideoEncoderConfiguration, _ns1__RemoveVideoEncoderConfigurationResponse &ns1__RemoveVideoEncoderConfigurationResponse);

	/// Web service operation 'RemoveVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveVideoSourceConfiguration(_ns1__RemoveVideoSourceConfiguration *ns1__RemoveVideoSourceConfiguration, _ns1__RemoveVideoSourceConfigurationResponse &ns1__RemoveVideoSourceConfigurationResponse) { return this->RemoveVideoSourceConfiguration(NULL, NULL, ns1__RemoveVideoSourceConfiguration, ns1__RemoveVideoSourceConfigurationResponse); }
	virtual	int RemoveVideoSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveVideoSourceConfiguration *ns1__RemoveVideoSourceConfiguration, _ns1__RemoveVideoSourceConfigurationResponse &ns1__RemoveVideoSourceConfigurationResponse);

	/// Web service operation 'RemoveAudioEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveAudioEncoderConfiguration(_ns1__RemoveAudioEncoderConfiguration *ns1__RemoveAudioEncoderConfiguration, _ns1__RemoveAudioEncoderConfigurationResponse &ns1__RemoveAudioEncoderConfigurationResponse) { return this->RemoveAudioEncoderConfiguration(NULL, NULL, ns1__RemoveAudioEncoderConfiguration, ns1__RemoveAudioEncoderConfigurationResponse); }
	virtual	int RemoveAudioEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveAudioEncoderConfiguration *ns1__RemoveAudioEncoderConfiguration, _ns1__RemoveAudioEncoderConfigurationResponse &ns1__RemoveAudioEncoderConfigurationResponse);

	/// Web service operation 'RemoveAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveAudioSourceConfiguration(_ns1__RemoveAudioSourceConfiguration *ns1__RemoveAudioSourceConfiguration, _ns1__RemoveAudioSourceConfigurationResponse &ns1__RemoveAudioSourceConfigurationResponse) { return this->RemoveAudioSourceConfiguration(NULL, NULL, ns1__RemoveAudioSourceConfiguration, ns1__RemoveAudioSourceConfigurationResponse); }
	virtual	int RemoveAudioSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveAudioSourceConfiguration *ns1__RemoveAudioSourceConfiguration, _ns1__RemoveAudioSourceConfigurationResponse &ns1__RemoveAudioSourceConfigurationResponse);

	/// Web service operation 'RemovePTZConfiguration' (returns error code or SOAP_OK)
	virtual	int RemovePTZConfiguration(_ns1__RemovePTZConfiguration *ns1__RemovePTZConfiguration, _ns1__RemovePTZConfigurationResponse &ns1__RemovePTZConfigurationResponse) { return this->RemovePTZConfiguration(NULL, NULL, ns1__RemovePTZConfiguration, ns1__RemovePTZConfigurationResponse); }
	virtual	int RemovePTZConfiguration(const char *endpoint, const char *soap_action, _ns1__RemovePTZConfiguration *ns1__RemovePTZConfiguration, _ns1__RemovePTZConfigurationResponse &ns1__RemovePTZConfigurationResponse);

	/// Web service operation 'RemoveVideoAnalyticsConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveVideoAnalyticsConfiguration(_ns1__RemoveVideoAnalyticsConfiguration *ns1__RemoveVideoAnalyticsConfiguration, _ns1__RemoveVideoAnalyticsConfigurationResponse &ns1__RemoveVideoAnalyticsConfigurationResponse) { return this->RemoveVideoAnalyticsConfiguration(NULL, NULL, ns1__RemoveVideoAnalyticsConfiguration, ns1__RemoveVideoAnalyticsConfigurationResponse); }
	virtual	int RemoveVideoAnalyticsConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveVideoAnalyticsConfiguration *ns1__RemoveVideoAnalyticsConfiguration, _ns1__RemoveVideoAnalyticsConfigurationResponse &ns1__RemoveVideoAnalyticsConfigurationResponse);

	/// Web service operation 'RemoveMetadataConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveMetadataConfiguration(_ns1__RemoveMetadataConfiguration *ns1__RemoveMetadataConfiguration, _ns1__RemoveMetadataConfigurationResponse &ns1__RemoveMetadataConfigurationResponse) { return this->RemoveMetadataConfiguration(NULL, NULL, ns1__RemoveMetadataConfiguration, ns1__RemoveMetadataConfigurationResponse); }
	virtual	int RemoveMetadataConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveMetadataConfiguration *ns1__RemoveMetadataConfiguration, _ns1__RemoveMetadataConfigurationResponse &ns1__RemoveMetadataConfigurationResponse);

	/// Web service operation 'RemoveAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveAudioOutputConfiguration(_ns1__RemoveAudioOutputConfiguration *ns1__RemoveAudioOutputConfiguration, _ns1__RemoveAudioOutputConfigurationResponse &ns1__RemoveAudioOutputConfigurationResponse) { return this->RemoveAudioOutputConfiguration(NULL, NULL, ns1__RemoveAudioOutputConfiguration, ns1__RemoveAudioOutputConfigurationResponse); }
	virtual	int RemoveAudioOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveAudioOutputConfiguration *ns1__RemoveAudioOutputConfiguration, _ns1__RemoveAudioOutputConfigurationResponse &ns1__RemoveAudioOutputConfigurationResponse);

	/// Web service operation 'RemoveAudioDecoderConfiguration' (returns error code or SOAP_OK)
	virtual	int RemoveAudioDecoderConfiguration(_ns1__RemoveAudioDecoderConfiguration *ns1__RemoveAudioDecoderConfiguration, _ns1__RemoveAudioDecoderConfigurationResponse &ns1__RemoveAudioDecoderConfigurationResponse) { return this->RemoveAudioDecoderConfiguration(NULL, NULL, ns1__RemoveAudioDecoderConfiguration, ns1__RemoveAudioDecoderConfigurationResponse); }
	virtual	int RemoveAudioDecoderConfiguration(const char *endpoint, const char *soap_action, _ns1__RemoveAudioDecoderConfiguration *ns1__RemoveAudioDecoderConfiguration, _ns1__RemoveAudioDecoderConfigurationResponse &ns1__RemoveAudioDecoderConfigurationResponse);

	/// Web service operation 'DeleteProfile' (returns error code or SOAP_OK)
	virtual	int DeleteProfile(_ns1__DeleteProfile *ns1__DeleteProfile, _ns1__DeleteProfileResponse &ns1__DeleteProfileResponse) { return this->DeleteProfile(NULL, NULL, ns1__DeleteProfile, ns1__DeleteProfileResponse); }
	virtual	int DeleteProfile(const char *endpoint, const char *soap_action, _ns1__DeleteProfile *ns1__DeleteProfile, _ns1__DeleteProfileResponse &ns1__DeleteProfileResponse);

	/// Web service operation 'GetVideoSourceConfigurations' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfigurations(_ns1__GetVideoSourceConfigurations *ns1__GetVideoSourceConfigurations, _ns1__GetVideoSourceConfigurationsResponse &ns1__GetVideoSourceConfigurationsResponse) { return this->GetVideoSourceConfigurations(NULL, NULL, ns1__GetVideoSourceConfigurations, ns1__GetVideoSourceConfigurationsResponse); }
	virtual	int GetVideoSourceConfigurations(const char *endpoint, const char *soap_action, _ns1__GetVideoSourceConfigurations *ns1__GetVideoSourceConfigurations, _ns1__GetVideoSourceConfigurationsResponse &ns1__GetVideoSourceConfigurationsResponse);

	/// Web service operation 'GetVideoEncoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetVideoEncoderConfigurations(_ns1__GetVideoEncoderConfigurations *ns1__GetVideoEncoderConfigurations, _ns1__GetVideoEncoderConfigurationsResponse &ns1__GetVideoEncoderConfigurationsResponse) { return this->GetVideoEncoderConfigurations(NULL, NULL, ns1__GetVideoEncoderConfigurations, ns1__GetVideoEncoderConfigurationsResponse); }
	virtual	int GetVideoEncoderConfigurations(const char *endpoint, const char *soap_action, _ns1__GetVideoEncoderConfigurations *ns1__GetVideoEncoderConfigurations, _ns1__GetVideoEncoderConfigurationsResponse &ns1__GetVideoEncoderConfigurationsResponse);

	/// Web service operation 'GetAudioSourceConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfigurations(_ns1__GetAudioSourceConfigurations *ns1__GetAudioSourceConfigurations, _ns1__GetAudioSourceConfigurationsResponse &ns1__GetAudioSourceConfigurationsResponse) { return this->GetAudioSourceConfigurations(NULL, NULL, ns1__GetAudioSourceConfigurations, ns1__GetAudioSourceConfigurationsResponse); }
	virtual	int GetAudioSourceConfigurations(const char *endpoint, const char *soap_action, _ns1__GetAudioSourceConfigurations *ns1__GetAudioSourceConfigurations, _ns1__GetAudioSourceConfigurationsResponse &ns1__GetAudioSourceConfigurationsResponse);

	/// Web service operation 'GetAudioEncoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioEncoderConfigurations(_ns1__GetAudioEncoderConfigurations *ns1__GetAudioEncoderConfigurations, _ns1__GetAudioEncoderConfigurationsResponse &ns1__GetAudioEncoderConfigurationsResponse) { return this->GetAudioEncoderConfigurations(NULL, NULL, ns1__GetAudioEncoderConfigurations, ns1__GetAudioEncoderConfigurationsResponse); }
	virtual	int GetAudioEncoderConfigurations(const char *endpoint, const char *soap_action, _ns1__GetAudioEncoderConfigurations *ns1__GetAudioEncoderConfigurations, _ns1__GetAudioEncoderConfigurationsResponse &ns1__GetAudioEncoderConfigurationsResponse);

	/// Web service operation 'GetVideoAnalyticsConfigurations' (returns error code or SOAP_OK)
	virtual	int GetVideoAnalyticsConfigurations(_ns1__GetVideoAnalyticsConfigurations *ns1__GetVideoAnalyticsConfigurations, _ns1__GetVideoAnalyticsConfigurationsResponse &ns1__GetVideoAnalyticsConfigurationsResponse) { return this->GetVideoAnalyticsConfigurations(NULL, NULL, ns1__GetVideoAnalyticsConfigurations, ns1__GetVideoAnalyticsConfigurationsResponse); }
	virtual	int GetVideoAnalyticsConfigurations(const char *endpoint, const char *soap_action, _ns1__GetVideoAnalyticsConfigurations *ns1__GetVideoAnalyticsConfigurations, _ns1__GetVideoAnalyticsConfigurationsResponse &ns1__GetVideoAnalyticsConfigurationsResponse);

	/// Web service operation 'GetMetadataConfigurations' (returns error code or SOAP_OK)
	virtual	int GetMetadataConfigurations(_ns1__GetMetadataConfigurations *ns1__GetMetadataConfigurations, _ns1__GetMetadataConfigurationsResponse &ns1__GetMetadataConfigurationsResponse) { return this->GetMetadataConfigurations(NULL, NULL, ns1__GetMetadataConfigurations, ns1__GetMetadataConfigurationsResponse); }
	virtual	int GetMetadataConfigurations(const char *endpoint, const char *soap_action, _ns1__GetMetadataConfigurations *ns1__GetMetadataConfigurations, _ns1__GetMetadataConfigurationsResponse &ns1__GetMetadataConfigurationsResponse);

	/// Web service operation 'GetAudioOutputConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfigurations(_ns1__GetAudioOutputConfigurations *ns1__GetAudioOutputConfigurations, _ns1__GetAudioOutputConfigurationsResponse &ns1__GetAudioOutputConfigurationsResponse) { return this->GetAudioOutputConfigurations(NULL, NULL, ns1__GetAudioOutputConfigurations, ns1__GetAudioOutputConfigurationsResponse); }
	virtual	int GetAudioOutputConfigurations(const char *endpoint, const char *soap_action, _ns1__GetAudioOutputConfigurations *ns1__GetAudioOutputConfigurations, _ns1__GetAudioOutputConfigurationsResponse &ns1__GetAudioOutputConfigurationsResponse);

	/// Web service operation 'GetAudioDecoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetAudioDecoderConfigurations(_ns1__GetAudioDecoderConfigurations *ns1__GetAudioDecoderConfigurations, _ns1__GetAudioDecoderConfigurationsResponse &ns1__GetAudioDecoderConfigurationsResponse) { return this->GetAudioDecoderConfigurations(NULL, NULL, ns1__GetAudioDecoderConfigurations, ns1__GetAudioDecoderConfigurationsResponse); }
	virtual	int GetAudioDecoderConfigurations(const char *endpoint, const char *soap_action, _ns1__GetAudioDecoderConfigurations *ns1__GetAudioDecoderConfigurations, _ns1__GetAudioDecoderConfigurationsResponse &ns1__GetAudioDecoderConfigurationsResponse);

	/// Web service operation 'GetVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfiguration(_ns1__GetVideoSourceConfiguration *ns1__GetVideoSourceConfiguration, _ns1__GetVideoSourceConfigurationResponse &ns1__GetVideoSourceConfigurationResponse) { return this->GetVideoSourceConfiguration(NULL, NULL, ns1__GetVideoSourceConfiguration, ns1__GetVideoSourceConfigurationResponse); }
	virtual	int GetVideoSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__GetVideoSourceConfiguration *ns1__GetVideoSourceConfiguration, _ns1__GetVideoSourceConfigurationResponse &ns1__GetVideoSourceConfigurationResponse);

	/// Web service operation 'GetVideoEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int GetVideoEncoderConfiguration(_ns1__GetVideoEncoderConfiguration *ns1__GetVideoEncoderConfiguration, _ns1__GetVideoEncoderConfigurationResponse &ns1__GetVideoEncoderConfigurationResponse) { return this->GetVideoEncoderConfiguration(NULL, NULL, ns1__GetVideoEncoderConfiguration, ns1__GetVideoEncoderConfigurationResponse); }
	virtual	int GetVideoEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__GetVideoEncoderConfiguration *ns1__GetVideoEncoderConfiguration, _ns1__GetVideoEncoderConfigurationResponse &ns1__GetVideoEncoderConfigurationResponse);

	/// Web service operation 'GetAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfiguration(_ns1__GetAudioSourceConfiguration *ns1__GetAudioSourceConfiguration, _ns1__GetAudioSourceConfigurationResponse &ns1__GetAudioSourceConfigurationResponse) { return this->GetAudioSourceConfiguration(NULL, NULL, ns1__GetAudioSourceConfiguration, ns1__GetAudioSourceConfigurationResponse); }
	virtual	int GetAudioSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__GetAudioSourceConfiguration *ns1__GetAudioSourceConfiguration, _ns1__GetAudioSourceConfigurationResponse &ns1__GetAudioSourceConfigurationResponse);

	/// Web service operation 'GetAudioEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioEncoderConfiguration(_ns1__GetAudioEncoderConfiguration *ns1__GetAudioEncoderConfiguration, _ns1__GetAudioEncoderConfigurationResponse &ns1__GetAudioEncoderConfigurationResponse) { return this->GetAudioEncoderConfiguration(NULL, NULL, ns1__GetAudioEncoderConfiguration, ns1__GetAudioEncoderConfigurationResponse); }
	virtual	int GetAudioEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__GetAudioEncoderConfiguration *ns1__GetAudioEncoderConfiguration, _ns1__GetAudioEncoderConfigurationResponse &ns1__GetAudioEncoderConfigurationResponse);

	/// Web service operation 'GetVideoAnalyticsConfiguration' (returns error code or SOAP_OK)
	virtual	int GetVideoAnalyticsConfiguration(_ns1__GetVideoAnalyticsConfiguration *ns1__GetVideoAnalyticsConfiguration, _ns1__GetVideoAnalyticsConfigurationResponse &ns1__GetVideoAnalyticsConfigurationResponse) { return this->GetVideoAnalyticsConfiguration(NULL, NULL, ns1__GetVideoAnalyticsConfiguration, ns1__GetVideoAnalyticsConfigurationResponse); }
	virtual	int GetVideoAnalyticsConfiguration(const char *endpoint, const char *soap_action, _ns1__GetVideoAnalyticsConfiguration *ns1__GetVideoAnalyticsConfiguration, _ns1__GetVideoAnalyticsConfigurationResponse &ns1__GetVideoAnalyticsConfigurationResponse);

	/// Web service operation 'GetMetadataConfiguration' (returns error code or SOAP_OK)
	virtual	int GetMetadataConfiguration(_ns1__GetMetadataConfiguration *ns1__GetMetadataConfiguration, _ns1__GetMetadataConfigurationResponse &ns1__GetMetadataConfigurationResponse) { return this->GetMetadataConfiguration(NULL, NULL, ns1__GetMetadataConfiguration, ns1__GetMetadataConfigurationResponse); }
	virtual	int GetMetadataConfiguration(const char *endpoint, const char *soap_action, _ns1__GetMetadataConfiguration *ns1__GetMetadataConfiguration, _ns1__GetMetadataConfigurationResponse &ns1__GetMetadataConfigurationResponse);

	/// Web service operation 'GetAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfiguration(_ns1__GetAudioOutputConfiguration *ns1__GetAudioOutputConfiguration, _ns1__GetAudioOutputConfigurationResponse &ns1__GetAudioOutputConfigurationResponse) { return this->GetAudioOutputConfiguration(NULL, NULL, ns1__GetAudioOutputConfiguration, ns1__GetAudioOutputConfigurationResponse); }
	virtual	int GetAudioOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__GetAudioOutputConfiguration *ns1__GetAudioOutputConfiguration, _ns1__GetAudioOutputConfigurationResponse &ns1__GetAudioOutputConfigurationResponse);

	/// Web service operation 'GetAudioDecoderConfiguration' (returns error code or SOAP_OK)
	virtual	int GetAudioDecoderConfiguration(_ns1__GetAudioDecoderConfiguration *ns1__GetAudioDecoderConfiguration, _ns1__GetAudioDecoderConfigurationResponse &ns1__GetAudioDecoderConfigurationResponse) { return this->GetAudioDecoderConfiguration(NULL, NULL, ns1__GetAudioDecoderConfiguration, ns1__GetAudioDecoderConfigurationResponse); }
	virtual	int GetAudioDecoderConfiguration(const char *endpoint, const char *soap_action, _ns1__GetAudioDecoderConfiguration *ns1__GetAudioDecoderConfiguration, _ns1__GetAudioDecoderConfigurationResponse &ns1__GetAudioDecoderConfigurationResponse);

	/// Web service operation 'GetCompatibleVideoEncoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleVideoEncoderConfigurations(_ns1__GetCompatibleVideoEncoderConfigurations *ns1__GetCompatibleVideoEncoderConfigurations, _ns1__GetCompatibleVideoEncoderConfigurationsResponse &ns1__GetCompatibleVideoEncoderConfigurationsResponse) { return this->GetCompatibleVideoEncoderConfigurations(NULL, NULL, ns1__GetCompatibleVideoEncoderConfigurations, ns1__GetCompatibleVideoEncoderConfigurationsResponse); }
	virtual	int GetCompatibleVideoEncoderConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleVideoEncoderConfigurations *ns1__GetCompatibleVideoEncoderConfigurations, _ns1__GetCompatibleVideoEncoderConfigurationsResponse &ns1__GetCompatibleVideoEncoderConfigurationsResponse);

	/// Web service operation 'GetCompatibleVideoSourceConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleVideoSourceConfigurations(_ns1__GetCompatibleVideoSourceConfigurations *ns1__GetCompatibleVideoSourceConfigurations, _ns1__GetCompatibleVideoSourceConfigurationsResponse &ns1__GetCompatibleVideoSourceConfigurationsResponse) { return this->GetCompatibleVideoSourceConfigurations(NULL, NULL, ns1__GetCompatibleVideoSourceConfigurations, ns1__GetCompatibleVideoSourceConfigurationsResponse); }
	virtual	int GetCompatibleVideoSourceConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleVideoSourceConfigurations *ns1__GetCompatibleVideoSourceConfigurations, _ns1__GetCompatibleVideoSourceConfigurationsResponse &ns1__GetCompatibleVideoSourceConfigurationsResponse);

	/// Web service operation 'GetCompatibleAudioEncoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleAudioEncoderConfigurations(_ns1__GetCompatibleAudioEncoderConfigurations *ns1__GetCompatibleAudioEncoderConfigurations, _ns1__GetCompatibleAudioEncoderConfigurationsResponse &ns1__GetCompatibleAudioEncoderConfigurationsResponse) { return this->GetCompatibleAudioEncoderConfigurations(NULL, NULL, ns1__GetCompatibleAudioEncoderConfigurations, ns1__GetCompatibleAudioEncoderConfigurationsResponse); }
	virtual	int GetCompatibleAudioEncoderConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleAudioEncoderConfigurations *ns1__GetCompatibleAudioEncoderConfigurations, _ns1__GetCompatibleAudioEncoderConfigurationsResponse &ns1__GetCompatibleAudioEncoderConfigurationsResponse);

	/// Web service operation 'GetCompatibleAudioSourceConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleAudioSourceConfigurations(_ns1__GetCompatibleAudioSourceConfigurations *ns1__GetCompatibleAudioSourceConfigurations, _ns1__GetCompatibleAudioSourceConfigurationsResponse &ns1__GetCompatibleAudioSourceConfigurationsResponse) { return this->GetCompatibleAudioSourceConfigurations(NULL, NULL, ns1__GetCompatibleAudioSourceConfigurations, ns1__GetCompatibleAudioSourceConfigurationsResponse); }
	virtual	int GetCompatibleAudioSourceConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleAudioSourceConfigurations *ns1__GetCompatibleAudioSourceConfigurations, _ns1__GetCompatibleAudioSourceConfigurationsResponse &ns1__GetCompatibleAudioSourceConfigurationsResponse);

	/// Web service operation 'GetCompatibleVideoAnalyticsConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleVideoAnalyticsConfigurations(_ns1__GetCompatibleVideoAnalyticsConfigurations *ns1__GetCompatibleVideoAnalyticsConfigurations, _ns1__GetCompatibleVideoAnalyticsConfigurationsResponse &ns1__GetCompatibleVideoAnalyticsConfigurationsResponse) { return this->GetCompatibleVideoAnalyticsConfigurations(NULL, NULL, ns1__GetCompatibleVideoAnalyticsConfigurations, ns1__GetCompatibleVideoAnalyticsConfigurationsResponse); }
	virtual	int GetCompatibleVideoAnalyticsConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleVideoAnalyticsConfigurations *ns1__GetCompatibleVideoAnalyticsConfigurations, _ns1__GetCompatibleVideoAnalyticsConfigurationsResponse &ns1__GetCompatibleVideoAnalyticsConfigurationsResponse);

	/// Web service operation 'GetCompatibleMetadataConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleMetadataConfigurations(_ns1__GetCompatibleMetadataConfigurations *ns1__GetCompatibleMetadataConfigurations, _ns1__GetCompatibleMetadataConfigurationsResponse &ns1__GetCompatibleMetadataConfigurationsResponse) { return this->GetCompatibleMetadataConfigurations(NULL, NULL, ns1__GetCompatibleMetadataConfigurations, ns1__GetCompatibleMetadataConfigurationsResponse); }
	virtual	int GetCompatibleMetadataConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleMetadataConfigurations *ns1__GetCompatibleMetadataConfigurations, _ns1__GetCompatibleMetadataConfigurationsResponse &ns1__GetCompatibleMetadataConfigurationsResponse);

	/// Web service operation 'GetCompatibleAudioOutputConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleAudioOutputConfigurations(_ns1__GetCompatibleAudioOutputConfigurations *ns1__GetCompatibleAudioOutputConfigurations, _ns1__GetCompatibleAudioOutputConfigurationsResponse &ns1__GetCompatibleAudioOutputConfigurationsResponse) { return this->GetCompatibleAudioOutputConfigurations(NULL, NULL, ns1__GetCompatibleAudioOutputConfigurations, ns1__GetCompatibleAudioOutputConfigurationsResponse); }
	virtual	int GetCompatibleAudioOutputConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleAudioOutputConfigurations *ns1__GetCompatibleAudioOutputConfigurations, _ns1__GetCompatibleAudioOutputConfigurationsResponse &ns1__GetCompatibleAudioOutputConfigurationsResponse);

	/// Web service operation 'GetCompatibleAudioDecoderConfigurations' (returns error code or SOAP_OK)
	virtual	int GetCompatibleAudioDecoderConfigurations(_ns1__GetCompatibleAudioDecoderConfigurations *ns1__GetCompatibleAudioDecoderConfigurations, _ns1__GetCompatibleAudioDecoderConfigurationsResponse &ns1__GetCompatibleAudioDecoderConfigurationsResponse) { return this->GetCompatibleAudioDecoderConfigurations(NULL, NULL, ns1__GetCompatibleAudioDecoderConfigurations, ns1__GetCompatibleAudioDecoderConfigurationsResponse); }
	virtual	int GetCompatibleAudioDecoderConfigurations(const char *endpoint, const char *soap_action, _ns1__GetCompatibleAudioDecoderConfigurations *ns1__GetCompatibleAudioDecoderConfigurations, _ns1__GetCompatibleAudioDecoderConfigurationsResponse &ns1__GetCompatibleAudioDecoderConfigurationsResponse);

	/// Web service operation 'SetVideoSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoSourceConfiguration(_ns1__SetVideoSourceConfiguration *ns1__SetVideoSourceConfiguration, _ns1__SetVideoSourceConfigurationResponse &ns1__SetVideoSourceConfigurationResponse) { return this->SetVideoSourceConfiguration(NULL, NULL, ns1__SetVideoSourceConfiguration, ns1__SetVideoSourceConfigurationResponse); }
	virtual	int SetVideoSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__SetVideoSourceConfiguration *ns1__SetVideoSourceConfiguration, _ns1__SetVideoSourceConfigurationResponse &ns1__SetVideoSourceConfigurationResponse);

	/// Web service operation 'SetVideoEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoEncoderConfiguration(_ns1__SetVideoEncoderConfiguration *ns1__SetVideoEncoderConfiguration, _ns1__SetVideoEncoderConfigurationResponse &ns1__SetVideoEncoderConfigurationResponse) { return this->SetVideoEncoderConfiguration(NULL, NULL, ns1__SetVideoEncoderConfiguration, ns1__SetVideoEncoderConfigurationResponse); }
	virtual	int SetVideoEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__SetVideoEncoderConfiguration *ns1__SetVideoEncoderConfiguration, _ns1__SetVideoEncoderConfigurationResponse &ns1__SetVideoEncoderConfigurationResponse);

	/// Web service operation 'SetAudioSourceConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioSourceConfiguration(_ns1__SetAudioSourceConfiguration *ns1__SetAudioSourceConfiguration, _ns1__SetAudioSourceConfigurationResponse &ns1__SetAudioSourceConfigurationResponse) { return this->SetAudioSourceConfiguration(NULL, NULL, ns1__SetAudioSourceConfiguration, ns1__SetAudioSourceConfigurationResponse); }
	virtual	int SetAudioSourceConfiguration(const char *endpoint, const char *soap_action, _ns1__SetAudioSourceConfiguration *ns1__SetAudioSourceConfiguration, _ns1__SetAudioSourceConfigurationResponse &ns1__SetAudioSourceConfigurationResponse);

	/// Web service operation 'SetAudioEncoderConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioEncoderConfiguration(_ns1__SetAudioEncoderConfiguration *ns1__SetAudioEncoderConfiguration, _ns1__SetAudioEncoderConfigurationResponse &ns1__SetAudioEncoderConfigurationResponse) { return this->SetAudioEncoderConfiguration(NULL, NULL, ns1__SetAudioEncoderConfiguration, ns1__SetAudioEncoderConfigurationResponse); }
	virtual	int SetAudioEncoderConfiguration(const char *endpoint, const char *soap_action, _ns1__SetAudioEncoderConfiguration *ns1__SetAudioEncoderConfiguration, _ns1__SetAudioEncoderConfigurationResponse &ns1__SetAudioEncoderConfigurationResponse);

	/// Web service operation 'SetVideoAnalyticsConfiguration' (returns error code or SOAP_OK)
	virtual	int SetVideoAnalyticsConfiguration(_ns1__SetVideoAnalyticsConfiguration *ns1__SetVideoAnalyticsConfiguration, _ns1__SetVideoAnalyticsConfigurationResponse &ns1__SetVideoAnalyticsConfigurationResponse) { return this->SetVideoAnalyticsConfiguration(NULL, NULL, ns1__SetVideoAnalyticsConfiguration, ns1__SetVideoAnalyticsConfigurationResponse); }
	virtual	int SetVideoAnalyticsConfiguration(const char *endpoint, const char *soap_action, _ns1__SetVideoAnalyticsConfiguration *ns1__SetVideoAnalyticsConfiguration, _ns1__SetVideoAnalyticsConfigurationResponse &ns1__SetVideoAnalyticsConfigurationResponse);

	/// Web service operation 'SetMetadataConfiguration' (returns error code or SOAP_OK)
	virtual	int SetMetadataConfiguration(_ns1__SetMetadataConfiguration *ns1__SetMetadataConfiguration, _ns1__SetMetadataConfigurationResponse &ns1__SetMetadataConfigurationResponse) { return this->SetMetadataConfiguration(NULL, NULL, ns1__SetMetadataConfiguration, ns1__SetMetadataConfigurationResponse); }
	virtual	int SetMetadataConfiguration(const char *endpoint, const char *soap_action, _ns1__SetMetadataConfiguration *ns1__SetMetadataConfiguration, _ns1__SetMetadataConfigurationResponse &ns1__SetMetadataConfigurationResponse);

	/// Web service operation 'SetAudioOutputConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioOutputConfiguration(_ns1__SetAudioOutputConfiguration *ns1__SetAudioOutputConfiguration, _ns1__SetAudioOutputConfigurationResponse &ns1__SetAudioOutputConfigurationResponse) { return this->SetAudioOutputConfiguration(NULL, NULL, ns1__SetAudioOutputConfiguration, ns1__SetAudioOutputConfigurationResponse); }
	virtual	int SetAudioOutputConfiguration(const char *endpoint, const char *soap_action, _ns1__SetAudioOutputConfiguration *ns1__SetAudioOutputConfiguration, _ns1__SetAudioOutputConfigurationResponse &ns1__SetAudioOutputConfigurationResponse);

	/// Web service operation 'SetAudioDecoderConfiguration' (returns error code or SOAP_OK)
	virtual	int SetAudioDecoderConfiguration(_ns1__SetAudioDecoderConfiguration *ns1__SetAudioDecoderConfiguration, _ns1__SetAudioDecoderConfigurationResponse &ns1__SetAudioDecoderConfigurationResponse) { return this->SetAudioDecoderConfiguration(NULL, NULL, ns1__SetAudioDecoderConfiguration, ns1__SetAudioDecoderConfigurationResponse); }
	virtual	int SetAudioDecoderConfiguration(const char *endpoint, const char *soap_action, _ns1__SetAudioDecoderConfiguration *ns1__SetAudioDecoderConfiguration, _ns1__SetAudioDecoderConfigurationResponse &ns1__SetAudioDecoderConfigurationResponse);

	/// Web service operation 'GetVideoSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceConfigurationOptions(_ns1__GetVideoSourceConfigurationOptions *ns1__GetVideoSourceConfigurationOptions, _ns1__GetVideoSourceConfigurationOptionsResponse &ns1__GetVideoSourceConfigurationOptionsResponse) { return this->GetVideoSourceConfigurationOptions(NULL, NULL, ns1__GetVideoSourceConfigurationOptions, ns1__GetVideoSourceConfigurationOptionsResponse); }
	virtual	int GetVideoSourceConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetVideoSourceConfigurationOptions *ns1__GetVideoSourceConfigurationOptions, _ns1__GetVideoSourceConfigurationOptionsResponse &ns1__GetVideoSourceConfigurationOptionsResponse);

	/// Web service operation 'GetVideoEncoderConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetVideoEncoderConfigurationOptions(_ns1__GetVideoEncoderConfigurationOptions *ns1__GetVideoEncoderConfigurationOptions, _ns1__GetVideoEncoderConfigurationOptionsResponse &ns1__GetVideoEncoderConfigurationOptionsResponse) { return this->GetVideoEncoderConfigurationOptions(NULL, NULL, ns1__GetVideoEncoderConfigurationOptions, ns1__GetVideoEncoderConfigurationOptionsResponse); }
	virtual	int GetVideoEncoderConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetVideoEncoderConfigurationOptions *ns1__GetVideoEncoderConfigurationOptions, _ns1__GetVideoEncoderConfigurationOptionsResponse &ns1__GetVideoEncoderConfigurationOptionsResponse);

	/// Web service operation 'GetAudioSourceConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioSourceConfigurationOptions(_ns1__GetAudioSourceConfigurationOptions *ns1__GetAudioSourceConfigurationOptions, _ns1__GetAudioSourceConfigurationOptionsResponse &ns1__GetAudioSourceConfigurationOptionsResponse) { return this->GetAudioSourceConfigurationOptions(NULL, NULL, ns1__GetAudioSourceConfigurationOptions, ns1__GetAudioSourceConfigurationOptionsResponse); }
	virtual	int GetAudioSourceConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetAudioSourceConfigurationOptions *ns1__GetAudioSourceConfigurationOptions, _ns1__GetAudioSourceConfigurationOptionsResponse &ns1__GetAudioSourceConfigurationOptionsResponse);

	/// Web service operation 'GetAudioEncoderConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioEncoderConfigurationOptions(_ns1__GetAudioEncoderConfigurationOptions *ns1__GetAudioEncoderConfigurationOptions, _ns1__GetAudioEncoderConfigurationOptionsResponse &ns1__GetAudioEncoderConfigurationOptionsResponse) { return this->GetAudioEncoderConfigurationOptions(NULL, NULL, ns1__GetAudioEncoderConfigurationOptions, ns1__GetAudioEncoderConfigurationOptionsResponse); }
	virtual	int GetAudioEncoderConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetAudioEncoderConfigurationOptions *ns1__GetAudioEncoderConfigurationOptions, _ns1__GetAudioEncoderConfigurationOptionsResponse &ns1__GetAudioEncoderConfigurationOptionsResponse);

	/// Web service operation 'GetMetadataConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetMetadataConfigurationOptions(_ns1__GetMetadataConfigurationOptions *ns1__GetMetadataConfigurationOptions, _ns1__GetMetadataConfigurationOptionsResponse &ns1__GetMetadataConfigurationOptionsResponse) { return this->GetMetadataConfigurationOptions(NULL, NULL, ns1__GetMetadataConfigurationOptions, ns1__GetMetadataConfigurationOptionsResponse); }
	virtual	int GetMetadataConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetMetadataConfigurationOptions *ns1__GetMetadataConfigurationOptions, _ns1__GetMetadataConfigurationOptionsResponse &ns1__GetMetadataConfigurationOptionsResponse);

	/// Web service operation 'GetAudioOutputConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioOutputConfigurationOptions(_ns1__GetAudioOutputConfigurationOptions *ns1__GetAudioOutputConfigurationOptions, _ns1__GetAudioOutputConfigurationOptionsResponse &ns1__GetAudioOutputConfigurationOptionsResponse) { return this->GetAudioOutputConfigurationOptions(NULL, NULL, ns1__GetAudioOutputConfigurationOptions, ns1__GetAudioOutputConfigurationOptionsResponse); }
	virtual	int GetAudioOutputConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetAudioOutputConfigurationOptions *ns1__GetAudioOutputConfigurationOptions, _ns1__GetAudioOutputConfigurationOptionsResponse &ns1__GetAudioOutputConfigurationOptionsResponse);

	/// Web service operation 'GetAudioDecoderConfigurationOptions' (returns error code or SOAP_OK)
	virtual	int GetAudioDecoderConfigurationOptions(_ns1__GetAudioDecoderConfigurationOptions *ns1__GetAudioDecoderConfigurationOptions, _ns1__GetAudioDecoderConfigurationOptionsResponse &ns1__GetAudioDecoderConfigurationOptionsResponse) { return this->GetAudioDecoderConfigurationOptions(NULL, NULL, ns1__GetAudioDecoderConfigurationOptions, ns1__GetAudioDecoderConfigurationOptionsResponse); }
	virtual	int GetAudioDecoderConfigurationOptions(const char *endpoint, const char *soap_action, _ns1__GetAudioDecoderConfigurationOptions *ns1__GetAudioDecoderConfigurationOptions, _ns1__GetAudioDecoderConfigurationOptionsResponse &ns1__GetAudioDecoderConfigurationOptionsResponse);

	/// Web service operation 'GetGuaranteedNumberOfVideoEncoderInstances' (returns error code or SOAP_OK)
	virtual	int GetGuaranteedNumberOfVideoEncoderInstances(_ns1__GetGuaranteedNumberOfVideoEncoderInstances *ns1__GetGuaranteedNumberOfVideoEncoderInstances, _ns1__GetGuaranteedNumberOfVideoEncoderInstancesResponse &ns1__GetGuaranteedNumberOfVideoEncoderInstancesResponse) { return this->GetGuaranteedNumberOfVideoEncoderInstances(NULL, NULL, ns1__GetGuaranteedNumberOfVideoEncoderInstances, ns1__GetGuaranteedNumberOfVideoEncoderInstancesResponse); }
	virtual	int GetGuaranteedNumberOfVideoEncoderInstances(const char *endpoint, const char *soap_action, _ns1__GetGuaranteedNumberOfVideoEncoderInstances *ns1__GetGuaranteedNumberOfVideoEncoderInstances, _ns1__GetGuaranteedNumberOfVideoEncoderInstancesResponse &ns1__GetGuaranteedNumberOfVideoEncoderInstancesResponse);

	/// Web service operation 'GetStreamUri' (returns error code or SOAP_OK)
	virtual	int GetStreamUri(_ns1__GetStreamUri *ns1__GetStreamUri, _ns1__GetStreamUriResponse &ns1__GetStreamUriResponse) { return this->GetStreamUri(NULL, NULL, ns1__GetStreamUri, ns1__GetStreamUriResponse); }
	virtual	int GetStreamUri(const char *endpoint, const char *soap_action, _ns1__GetStreamUri *ns1__GetStreamUri, _ns1__GetStreamUriResponse &ns1__GetStreamUriResponse);

	/// Web service operation 'StartMulticastStreaming' (returns error code or SOAP_OK)
	virtual	int StartMulticastStreaming(_ns1__StartMulticastStreaming *ns1__StartMulticastStreaming, _ns1__StartMulticastStreamingResponse &ns1__StartMulticastStreamingResponse) { return this->StartMulticastStreaming(NULL, NULL, ns1__StartMulticastStreaming, ns1__StartMulticastStreamingResponse); }
	virtual	int StartMulticastStreaming(const char *endpoint, const char *soap_action, _ns1__StartMulticastStreaming *ns1__StartMulticastStreaming, _ns1__StartMulticastStreamingResponse &ns1__StartMulticastStreamingResponse);

	/// Web service operation 'StopMulticastStreaming' (returns error code or SOAP_OK)
	virtual	int StopMulticastStreaming(_ns1__StopMulticastStreaming *ns1__StopMulticastStreaming, _ns1__StopMulticastStreamingResponse &ns1__StopMulticastStreamingResponse) { return this->StopMulticastStreaming(NULL, NULL, ns1__StopMulticastStreaming, ns1__StopMulticastStreamingResponse); }
	virtual	int StopMulticastStreaming(const char *endpoint, const char *soap_action, _ns1__StopMulticastStreaming *ns1__StopMulticastStreaming, _ns1__StopMulticastStreamingResponse &ns1__StopMulticastStreamingResponse);

	/// Web service operation 'SetSynchronizationPoint' (returns error code or SOAP_OK)
	virtual	int SetSynchronizationPoint(_ns1__SetSynchronizationPoint *ns1__SetSynchronizationPoint, _ns1__SetSynchronizationPointResponse &ns1__SetSynchronizationPointResponse) { return this->SetSynchronizationPoint(NULL, NULL, ns1__SetSynchronizationPoint, ns1__SetSynchronizationPointResponse); }
	virtual	int SetSynchronizationPoint(const char *endpoint, const char *soap_action, _ns1__SetSynchronizationPoint *ns1__SetSynchronizationPoint, _ns1__SetSynchronizationPointResponse &ns1__SetSynchronizationPointResponse);

	/// Web service operation 'GetSnapshotUri' (returns error code or SOAP_OK)
	virtual	int GetSnapshotUri(_ns1__GetSnapshotUri *ns1__GetSnapshotUri, _ns1__GetSnapshotUriResponse &ns1__GetSnapshotUriResponse) { return this->GetSnapshotUri(NULL, NULL, ns1__GetSnapshotUri, ns1__GetSnapshotUriResponse); }
	virtual	int GetSnapshotUri(const char *endpoint, const char *soap_action, _ns1__GetSnapshotUri *ns1__GetSnapshotUri, _ns1__GetSnapshotUriResponse &ns1__GetSnapshotUriResponse);

	/// Web service operation 'GetVideoSourceModes' (returns error code or SOAP_OK)
	virtual	int GetVideoSourceModes(_ns1__GetVideoSourceModes *ns1__GetVideoSourceModes, _ns1__GetVideoSourceModesResponse &ns1__GetVideoSourceModesResponse) { return this->GetVideoSourceModes(NULL, NULL, ns1__GetVideoSourceModes, ns1__GetVideoSourceModesResponse); }
	virtual	int GetVideoSourceModes(const char *endpoint, const char *soap_action, _ns1__GetVideoSourceModes *ns1__GetVideoSourceModes, _ns1__GetVideoSourceModesResponse &ns1__GetVideoSourceModesResponse);

	/// Web service operation 'SetVideoSourceMode' (returns error code or SOAP_OK)
	virtual	int SetVideoSourceMode(_ns1__SetVideoSourceMode *ns1__SetVideoSourceMode, _ns1__SetVideoSourceModeResponse &ns1__SetVideoSourceModeResponse) { return this->SetVideoSourceMode(NULL, NULL, ns1__SetVideoSourceMode, ns1__SetVideoSourceModeResponse); }
	virtual	int SetVideoSourceMode(const char *endpoint, const char *soap_action, _ns1__SetVideoSourceMode *ns1__SetVideoSourceMode, _ns1__SetVideoSourceModeResponse &ns1__SetVideoSourceModeResponse);

	/// Web service operation 'GetOSDs' (returns error code or SOAP_OK)
	virtual	int GetOSDs(_ns1__GetOSDs *ns1__GetOSDs, _ns1__GetOSDsResponse &ns1__GetOSDsResponse) { return this->GetOSDs(NULL, NULL, ns1__GetOSDs, ns1__GetOSDsResponse); }
	virtual	int GetOSDs(const char *endpoint, const char *soap_action, _ns1__GetOSDs *ns1__GetOSDs, _ns1__GetOSDsResponse &ns1__GetOSDsResponse);

	/// Web service operation 'GetOSD' (returns error code or SOAP_OK)
	virtual	int GetOSD(_ns1__GetOSD *ns1__GetOSD, _ns1__GetOSDResponse &ns1__GetOSDResponse) { return this->GetOSD(NULL, NULL, ns1__GetOSD, ns1__GetOSDResponse); }
	virtual	int GetOSD(const char *endpoint, const char *soap_action, _ns1__GetOSD *ns1__GetOSD, _ns1__GetOSDResponse &ns1__GetOSDResponse);

	/// Web service operation 'GetOSDOptions' (returns error code or SOAP_OK)
	virtual	int GetOSDOptions(_ns1__GetOSDOptions *ns1__GetOSDOptions, _ns1__GetOSDOptionsResponse &ns1__GetOSDOptionsResponse) { return this->GetOSDOptions(NULL, NULL, ns1__GetOSDOptions, ns1__GetOSDOptionsResponse); }
	virtual	int GetOSDOptions(const char *endpoint, const char *soap_action, _ns1__GetOSDOptions *ns1__GetOSDOptions, _ns1__GetOSDOptionsResponse &ns1__GetOSDOptionsResponse);

	/// Web service operation 'SetOSD' (returns error code or SOAP_OK)
	virtual	int SetOSD(_ns1__SetOSD *ns1__SetOSD, _ns1__SetOSDResponse &ns1__SetOSDResponse) { return this->SetOSD(NULL, NULL, ns1__SetOSD, ns1__SetOSDResponse); }
	virtual	int SetOSD(const char *endpoint, const char *soap_action, _ns1__SetOSD *ns1__SetOSD, _ns1__SetOSDResponse &ns1__SetOSDResponse);

	/// Web service operation 'CreateOSD' (returns error code or SOAP_OK)
	virtual	int CreateOSD(_ns1__CreateOSD *ns1__CreateOSD, _ns1__CreateOSDResponse &ns1__CreateOSDResponse) { return this->CreateOSD(NULL, NULL, ns1__CreateOSD, ns1__CreateOSDResponse); }
	virtual	int CreateOSD(const char *endpoint, const char *soap_action, _ns1__CreateOSD *ns1__CreateOSD, _ns1__CreateOSDResponse &ns1__CreateOSDResponse);

	/// Web service operation 'DeleteOSD' (returns error code or SOAP_OK)
	virtual	int DeleteOSD(_ns1__DeleteOSD *ns1__DeleteOSD, _ns1__DeleteOSDResponse &ns1__DeleteOSDResponse) { return this->DeleteOSD(NULL, NULL, ns1__DeleteOSD, ns1__DeleteOSDResponse); }
	virtual	int DeleteOSD(const char *endpoint, const char *soap_action, _ns1__DeleteOSD *ns1__DeleteOSD, _ns1__DeleteOSDResponse &ns1__DeleteOSDResponse);
};
#endif
